routes/web.php
<?php

Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

//VISITORS

Route::get('home2', 'VisitorsController@homeVisitors')->name('v.home');

        //RESEARCHERS
        Route::get('home2/researchers', 'VisitorsController@indexResearchers')->name('r.index');
        Route::get('home2/researchers/{id}', 'VisitorsController@showResearchers')->name('r.show');

        //LOTS
        Route::get('home2/lots', 'VisitorsController@indexLots')->name('l.index');
        Route::get('home2/lots/{id}', 'VisitorsController@showLots')->name('l.show');

        //ESTABLISHMENTS
        Route::get('home2/establishments', 'VisitorsController@indexEstablishments')->name('e.index');
        Route::get('home2/establishments/{id}', 'VisitorsController@showEstablishments')->name('e.show');
        Route::get('map2/{id}', 'EstablishmentsController@showMapVisitor');

//GEOLOCATION
Route::get('map/{id}', 'EstablishmentsController@showMap')->middleware('auth');


//IMAGES
Route::post('imagePostEstablishment', 'ImageController@imagePostEstablishments')->middleware('auth')->name('imagePostEstablishment');

Route::post('imagePostResearcher', 'ImageController@imagePostResearchers')->middleware('auth')->name('imagePostResearcher');


//HOME
Route::resource('home', 'HomeController')->middleware('auth');

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');


//RESEARCHERS
Route::put('researchers/newphone', 'ResearchersController@newPhone')->middleware('auth')->name('r.newphone');

Route::put('researchers/newadr', 'ResearchersController@newAddr')->middleware('auth')->name('r.newad');

Route::put('researchers/link', 'ResearchersController@link')->middleware('auth')->name('r.link');

Route::put('researchers/tolot', 'ResearchersController@toLot')->middleware('auth')->name('r.lot');

Route::delete('researchers/unlink', 'ResearchersController@unlink')->middleware('auth')->name('unlink');

Route::delete('researchers/deletelot', 'ResearchersController@deleteLot')->middleware('auth')->name('deleteLot');

Route::put('researchers/deletephoto', 'ResearchersController@deletePhoto')->middleware('auth')->name('r.deletephoto');

Route::delete('researchers/deletephone', 'ResearchersController@deletePhone')->middleware('auth')->name('r.deletep');

Route::delete('researchers/deleteaddress', 'ResearchersController@deleteAddress')->middleware('auth')->name('r.deletea');

Route::get('researchers/editaddress/{id}', 'ResearchersController@showEditAddress')->middleware('auth')->name('r.showeditaddress');

Route::put('researchers/{id}/editaddress', 'ResearchersController@editAddress')->middleware('auth')->name('r.editaddress');

Route::resource('researchers', 'ResearchersController')->middleware('auth');


//ESTABLISHMENTS
Route::put('establishments/newphone', 'EstablishmentsController@newPhone')->middleware('auth')->name('e.newphone');

Route::put('establishments/newaddress', 'EstablishmentsController@newAddr')->middleware('auth')->name('e.newad');

Route::delete('establishments/deletephone', 'EstablishmentsController@deletePhone')->middleware('auth')->name('e.deletep');

Route::delete('establishments/deleteaddress', 'EstablishmentsController@deleteAddress')->middleware('auth')->name('e.deletea');

Route::get('establishments/editaddress/{id}', 'EstablishmentsController@showEditAddress')->middleware('auth')->name('e.showeditaddress');

Route::put('establishments/{id}/editaddress', 'EstablishmentsController@editAddress')->middleware('auth')->name('e.editaddress');

Route::put('establishments/deletephoto', 'EstablishmentsController@deletePhoto')->middleware('auth')->name('e.deletephoto');

Route::resource('establishments', 'EstablishmentsController')->middleware('auth');

//WORK LOTS

Route::resource('lots', 'LotsController')->middleware('auth');













































// Route::resource('adr_researcher', 'AdrResearcherController')->middleware('auth');

// Route::resource('adr_establishments', 'AdrEstablishmentsController')->middleware('auth');
// Route::resource('est_phone', 'EstPhoneController')->middleware('auth');

// 
// Route::get('researchers/', 'ResearchersController@index')->middleware('auth');
// Route::get('researchers/{id}', 'ResearchersController@show')->middleware('auth');
// Route::put('researchers', 'ResearchersController@edit')->middleware('auth');
// Route::delete('delete/{id}',array('uses' => 'ResearchersController@destroy', 'as' => 'deleteroute'))->middleware('auth');

app/Researcher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Establishment;
use App\Res_Phone;
use App\Adr_Researcher;
use App\Lot;
use DB;

class Researcher extends Model
{
    //use SoftDeletes;

    protected $table = 'researchers';
    protected $fillable = [
        'name',
        'national_id',
        'email',
        'url_curriculum',
        'url_photo',
        'c_summary'
    ];

    public function resPhones(){
        return $this->hasMany('App\Res_Phone');
    }

    public function adrResearchers(){
        return $this->hasMany('App\Adr_Researcher');
    }

    public function establishments(){
        return $this->belongsToMany('App\Establishment', 'establishments_researchers');
    }

    public function lots(){
        return $this->belongsToMany('App\Lot', 'researchers_lots');
    }
    
}

app/Http/Controllers/ResearchersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Researcher;
use App\Establishment;
use App\Res_Phone as Phone;
use App\Adr_Researcher as Adr;
use App\Establishments_Researchers as Er;
use App\Researchers_Lots as Rl;
use App\ImageController;
use App\Lot;
use Auth;
use DB;

class ResearchersController extends Controller
{
    //SHOW//

    public function index()
    {
        $researchers = DB::table('researchers')
        ->orderBy('name', 'asc')->get();        

         return view('researchers.index', ['researchers'=> $researchers]);
    }

    public function show($id)
    {
        $researcher = Researcher::find($id); 
        $establishments = Establishment::all();
        $lots = Lot::all();
        $rl = Rl::where('researcher_id','=', $id)->get();
        $er = Er::where('researcher_id','=', $id)->get();

        return view('researchers.show', ['researcher'=> $researcher, 'establishments'=> $establishments, 'er'=> $er, 'lots'=> $lots, 'rl'=> $rl]);
    }

    public function showEditAddress($id)
    {
      $adr = Adr::find($id);
      return view('researchers.editaddress', ['adr'=> $adr]);
    }

    //CREATES//

    public function link(Request $request)
    {   
        if(Establishment::find($request->input('establishmentId')))
        {
        Er::create([
            'researcher_id' => $request->input('id'),
            'establishment_id' => $request->input('establishmentId')
        ]);
        }
        
        return back();
    }

    public function toLot(Request $request)
    {   
        if(Lot::find($request->input('lotId')))
        {
        Rl::create([
            'researcher_id' => $request->input('id'),
            'lot_id' => $request->input('lotId')
        ]);
        }
        
        return back();
    }


    public function newPhone(Request $request)
    {
        Phone::create([
         'researcher_id' => $request->input('id'),
         'ddi' => $request->input('ddi'),
         'ddd' => $request->input('ddd'),
         'phone' => $request->input('phone')
        ]);
 
        return back();
    }

    public function newAddr(Request $request)
    {
       Adr::create([
        'researcher_id' => $request->input('id'),
        'address' => $request->input('address'),
        'postal_code' => $request->input('postal_code'),
        'city' => $request->input('city'),
        'country' => $request->input('country'),
        'state' => $request->input('state')
        ]);

        return back();
    }   

    public function create(Researcher $researcher)
    {   
        return view('researchers.create', ['researcher'=> $researcher]);
    }

    private function registerPhone(Request $request, $researcherId)
    {
        return Phone::create([
            'ddi' => $request->input('ddi'),
            'ddd' => $request->input('ddd'),
            'phone' => $request->input('phone'),
            'researcher_id' => $researcherId
        ]);
    }

    private function registerAddress(Request $request, $researcherId)
    {
        return Adr::create([
            'address' => $request->input('address'),
            'postal_code' => $request->input('postal_code'),
            'city' => $request->input('city'),
            'country' => $request->input('country'),
            'state' => $request->input('state'),
            'researcher_id' => $researcherId
        ]);
    }

    public function store(Request $request)
    {
        if (Auth::check()){
            $researcher = Researcher::create([
                'name' => $request->input('name'),
                'national_id' => $request->input('national_id'),
                'email' => $request->input('email'),
                'url_curriculum' => $request->input('url_curriculum'),
                'url_photo' => $request->input('url_photo'),
                'c_summary' => $request->input('c_summary'),
                'user_id' => Auth::user()->id
            ]);

        $this->registerAddress($request, $researcher->id);
        $this->registerPhone($request, $researcher->id);
            
        if($researcher){
            return redirect()->route('researchers.show', ['researcher' => $researcher->id]);
            }
    }
        
    return back()->withInput()->with('error' , 'Algo deu errado :(');
    }

   //SAVES//

    public function edit($id)
    {
       $researcher = Researcher::find($id);       
       return view('researchers.edit', ['researcher'=> $researcher]);
    }

    public function update(Request $request, $id)
    {
        $reseacherUpdate = Researcher::where('id', $id)
        ->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'national_id' => $request->input('national_id'),
            'c_summary' => $request->input('c_summary'),
            'url_curriculum' => $request->input('url_curriculum')

        ]);

        if($reseacherUpdate){
            return redirect()->route('researchers.show', ['researcher'=>$id]);
        }
        return back()->withInput();
    }

    public function editAddress(Request $request, $id)
    {
        $a_update = Adr::where('id', $id)
        ->update([
            'address' => $request->input('address'),
            'postal_code' => $request->input('postal_code'),
            'city' => $request->input('city'),
            'country' => $request->input('country'),
            'state' => $request->input('state')
        ]);
        $researcher = $request->input('researcher_id');
        return redirect()->route('researchers.show' , ['researcher' => $researcher]);
    }

    //DELETES//

   public function destroy($id)
   {
       $find = Researcher::find($id);
       if($find->delete())
       {
            return redirect()->route('researchers.index')
            ->with('success', 'Algo deu certo!');
       }
       return back()->withInput()->with('error', 'Algo deu errado... pesquisador não removido!');
   }

    public function deletePhone(Request $request)
    {
        Phone::destroy([
            'id' => $request->input('id')
        ]);
        
        return back();
    }

    public function deleteAddress(Request $request)
    {
        Adr::destroy([
            'id' => $request->input('id')
        ]);
        
        return back();
    }

    public function unlink(Request $request)
    {
        Er::destroy([
            'id' => $request->input('id')
        ]);
        
        return back();
    }

    public function deleteLot(Request $request)
    {
        Rl::destroy([
            'id' => $request->input('id')
        ]);
        
        return back();
    }

    public function deletePhoto(Request $request)
    {
        $id = $request->input('id');
        $deletep = Researcher::where('id', $id)
        ->update(['url_photo' => $request->input('url_photo')]);
        
        return back();
    }

}

resources/views/researchers/create.blade.php
<!--RESEARCHERS CREATE-->
@extends('layouts.app')

@section('content')


<div class="container" >
    <div class="row justify-content-center" style="margin-top: 5.5%">
        <div class="col-md-10">
            <div class="card">
              <div class="card-header"><a style="font-weight:bold">NOVO PESQUISADOR</a></div>                  
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                     
                        <ul class="list-group"></ul>  
                        <li class="list-group-item">
                        <form method="post" action="{{ route('researchers.store') }}">

                          {{ csrf_field() }}
                    
                          
                          <div class="form-row">

                          <div class="form-group col-md-10">
                          <label for="researcher-name">Nome Completo*</label>
                          <input type="text" 
                                 class="form-control" 
                                 id="researcher-name" 
                                 placeholder="Nome Completo do Pesquisador" 
                                 name="name"
                                 maxlength="60"
                                 required
                                 />
                          </div>

                          <div class="form-group col-md-2">
                            <label for="researcher-id">CPF*</label>
                            <input type="text" 
                                   class="form-control" 
                                   id="researcher-id" 
                                   placeholder="Apenas números!" 
                                   name="national_id"
                                   maxlength="45"
                                   required
                                   />
                            </div>  

                          </div>

                          <div class="form-row">

                        <div class="form-group col-md-4">
                            <label for="email">Email*</label>
                            <input type="email" 
                                    class="form-control" 
                                    id="inputPassword4" 
                                    placeholder="exemplo@email.com"
                                    name ="email"
                                    maxlength="45"
                                    required/>
                        </div>

                        <div class="form-group col-md-1">
                            <label for="researcher-ddi">DDI*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="researcher-ddi" 
                                    placeholder="Ex:55" 
                                    name="ddi"
                                    maxlength="4"
                                    required
                                    />
                        </div>  

                        <div class="form-group col-md-1">
                            <label for="researcher-ddd">DDD*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="researcher-ddd" 
                                    placeholder="Ex:61" 
                                    name="ddd"
                                    maxlength="2"
                                    required
                                    />
                        </div>  

                        <div class="form-group col-md-2">
                            <label for="researcher-phone">Telefone*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="researcher-phone" 
                                    placeholder="Apenas números!" 
                                    name="phone"
                                    maxlength="10"
                                    required
                                    />
                        </div>

                        <div class="form-group col-md-4">
                            <label for="researcher-link">Link do <a href="http://buscatextual.cnpq.br/buscatextual/busca.do?metodo=apresentar">Currículo Lattes</a></label>
                            <input type="text" 
                                    class="form-control" 
                                    id="researcher-link" 
                                    placeholder="Ex: http://cnpq.br/visualizacv.do?id=xxxx " 
                                    name="url_curriculum"
                                    maxlength="100"
                                    
                                    />
                        </div>                    
                        </div>
                         
                        Resumo do Currículo: <br>
                          <div class="input-group">      
                              <textarea class="form-control" 
                                        aria-label="With textarea"
                                        name="c_summary"
                              ></textarea>
                            </div>
                            <br>

                            <div class="form-row">
                            <div class="form-group col-md-2">
                                <label for="researcher-zip">CEP*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="researcher-zip" 
                                        placeholder="Apenas números!" 
                                        name="postal_code"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-4">
                                <label for="researcher-address">Endereço*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="researcher-address" 
                                        placeholder="Ex: Rua das Artes, Bairro Ipê casa 32" 
                                        name="address"
                                        maxlength="90"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-2">
                                <label for="researcher-city">Cidade*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="researcher-city" 
                                        placeholder="Ex:Brasília" 
                                        name="city"
                                        maxlength="50"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-1">
                                    <label for="researcher-state">UF*</label>
                                    <input type="text" 
                                    class="form-control" 
                                    id="researcher-state" 
                                    placeholder="Ex: DF" 
                                    name="state"
                                    maxlength="2"
                                    required
                                    />
                                    </div>   

                                <div class="form-group col-md-3">
                                    <label for="researcher-country">País*</label>
                                    <input type="text" 
                                    class="form-control" 
                                    id="researcher-country" 
                                    placeholder="Brasil" 
                                    name="country"
                                    maxlength="45"
                                    required
                                    />
                                </div>
                           <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>
                            </div>                                     
                                
                            <br>
                          <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                        <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-times"></i> Cancelar</a>
                  </form>                                                    
              </div>
            </div>
        </div>
    </div>
</div>

@endsection


                   

resources/views/researchers/edit.blade.php
<!--RESEARCHERS EDIT-->
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
   <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
      <div class="card-header">Editar dados de <a style="font-weight:bold">{{$researcher->name}}</a></div>                  
          <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <ul class="list-group"></ul>  
            <li class="list-group-item">
              <form method="post" action="{{ route('researchers.update', [$researcher->id]) }}">

                {{ csrf_field() }}
          
                <input type="hidden" name="_method" value="put">

                  <div class="form-row">
                    <div class="form-group col-md-7">
                      <label for="researcher-name">Nome*</label>
                      <input required 
                              type="text" 
                              class="form-control" 
                              id="researcher-name" 
                              value="{{ $researcher->name}}"
                              maxlength="60"
                              name="name"                                   
                              />
                      </div>
                    <div class="form-group col-md-5">
                      <label for="researcher-email">Email*</label>
                      <input required
                              type="email" 
                              class="form-control" 
                              id="researcher-email" 
                              value="{{ $researcher->email}}"
                              maxlength="45"
                              name="email"
                              />
                    </div>
                  </div>
                    
                    <div class="form-row">

                      <div class="form-group col-md-4">
                      <label for="researcher-id">CPF*</label>
                      <input type="text" 
                              class="form-control" 
                              id="researcher-id" 
                              value="{{ $researcher->national_id}}" 
                              name="national_id"
                              maxlength="45"
                              required
                              />
                      </div> 
                      
                      <div class="form-group col-md-8">
                        <label for="researcher-link">Link do <a href="http://buscatextual.cnpq.br/buscatextual/busca.do?metodo=apresentar">Currículo Lattes</a>*</label>
                        <input type="text" 
                                class="form-control" 
                                id="researcher-link" 
                                value="{{ $researcher->url_curriculum}}" 
                                name="url_curriculum"
                                maxlength="100"
                                required
                                />
                        </div>  

                      </div>  

                      <div class="form-row">

                        Resumo do Currículo* <br>
                      <div class="input-group">      
                          <textarea class="form-control" 
                                    aria-label="With textarea"
                                    name="c_summary"
                                    required
                          >{{ $researcher->c_summary}}
                        </textarea>
                        </div>
                        <br>
            <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos!(*)</i></a>
            <div style="margin-left:80%">
            <a class="btn btn-outline-danger" href="/researchers/{{$researcher->id}}">Cancelar</a>
            <input type="submit" class="btn btn-outline-success"  value="Salvar"/>

</div>
                  <!--FIM DO FORMULÁRIO-->
                  </form> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/researchers/editaddress.blade.php
{{-- RESEARCHER ADDRESS --}}
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
  <div class="row justify-content-center">
   <div class="col-md-10">
    <div class="card">
     <div class="card-header">Editar Endereço</a></div>                  
      <div class="card-body">
        @if (session('status'))
         <div class="alert alert-success">
          {{ session('status') }}
         </div>
         @endif 

         <form method="post" action="{{ route('r.editaddress', [$adr->id]) }}">

            {{ csrf_field() }}
      
        <input type="hidden" name="_method" value="put">
        
          <div class="form-row">
            <div class="form-group col-md-9">
              <label for="researcher-address">Endereço*</label>
              <input type="text" 
                     class="form-control" 
                     id="researcher-address" 
                     value="{{$adr->address}}" 
                     name="address"
                     maxlength="90"
                     required
                    />
            </div>
            
            <div class="form-group col-md-3">
              <label for="researcher-zip">CEP*</label>
              <input type="text" 
                     class="form-control" 
                     id="researcher-zip" 
                     value="{{$adr->postal_code}}" 
                     name="postal_code"
                     maxlength="20"
                     required
                     />
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-5">
              <label for="researcher-city">Cidade*</label>
              <input type="text" 
                     class="form-control" 
                     id="researcher-city" 
                     value="{{$adr->city}}" 
                     name="city"
                     maxlength="50"
                     required
                     />
            </div>

            <div class="form-group col-md-1">
             <label for="researcher-state">UF*</label>
             <input type="text" 
                   class="form-control" 
                   id="researcher-state" 
                   value="{{$adr->state}}" 
                   name="state"
                   maxlength="2"
                   required
                   />
                </div>   
              

              <div class="form-group col-md-6">
                <label for="researcher-country">País*</label>
                <input type="text" 
                       class="form-control" 
                       id="researcher-country" 
                       value="{{$adr->country}}" 
                       name="country"
                       maxlength="45"
                       required
                       />
              </div>

              <input type="text" 
                     class="form-control"
                     value="{{$adr->researcher_id}}" 
                     name="researcher_id"
                     style="display:none"
                     required
                     />

            </div>

<a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>

        <div style="margin-left:80%">
            <a class="btn btn-outline-danger" href="{{ URL::previous() }}">Cancelar</a>
            <input type="submit" class="btn btn-outline-success"  value="Salvar"/>
        </div>

        </form> 
</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/researchers/index.blade.php
<!--RESEARCHERS INDEX-->
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.5%">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">                
              <div class="card-header"><i class="fas fa-users"></i> Banco de Pesquisadores </div> 
                <div class="card-body">
                        
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <a class="btn btn-primary" href="/researchers/create"><i class="fas fa-plus"></i> Novo Pesquisador</a> <br>

                    @foreach($researchers as $researcher)
                    <br>
                    <li class="list-group-item">
                        @if ($researcher->url_photo)
                        <a href="/researchers/{{ $researcher->id }}">
                          <img src="{{ URL($researcher->url_photo) }}" class="p-img">
                        </a>
                        @else  
                        <a href="/researchers/{{ $researcher->id }}">
                          <img src="{{ URL('image/empty.png') }}" class="p-img">
                        </a>
                        @endif 
                    <a href="/researchers/{{ $researcher->id }}">  
                    {{ $researcher->name }}
                    </a>                           
                    @endforeach 
                    </li>                   
                    <br>
             
</div>     
</div>
</div>
</div>
</div>
@endsection