routes/web.php
<?php

Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

//VISITORS

Route::get('home2', 'VisitorsController@homeVisitors')->name('v.home');

        //RESEARCHERS
        Route::get('home2/researchers', 'VisitorsController@indexResearchers')->name('r.index');
        Route::get('home2/researchers/{id}', 'VisitorsController@showResearchers')->name('r.show');

        //LOTS
        Route::get('home2/lots', 'VisitorsController@indexLots')->name('l.index');
        Route::get('home2/lots/{id}', 'VisitorsController@showLots')->name('l.show');

        //ESTABLISHMENTS
        Route::get('home2/establishments', 'VisitorsController@indexEstablishments')->name('e.index');
        Route::get('home2/establishments/{id}', 'VisitorsController@showEstablishments')->name('e.show');
        Route::get('map2/{id}', 'EstablishmentsController@showMapVisitor');

//GEOLOCATION
Route::get('map/{id}', 'EstablishmentsController@showMap')->middleware('auth');


//IMAGES
Route::post('imagePostEstablishment', 'ImageController@imagePostEstablishments')->middleware('auth')->name('imagePostEstablishment');

Route::post('imagePostResearcher', 'ImageController@imagePostResearchers')->middleware('auth')->name('imagePostResearcher');


//HOME
Route::resource('home', 'HomeController')->middleware('auth');

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');


//RESEARCHERS
Route::put('researchers/newphone', 'ResearchersController@newPhone')->middleware('auth')->name('r.newphone');

Route::put('researchers/newadr', 'ResearchersController@newAddr')->middleware('auth')->name('r.newad');

Route::put('researchers/link', 'ResearchersController@link')->middleware('auth')->name('r.link');

Route::put('researchers/tolot', 'ResearchersController@toLot')->middleware('auth')->name('r.lot');

Route::delete('researchers/unlink', 'ResearchersController@unlink')->middleware('auth')->name('unlink');

Route::delete('researchers/deletelot', 'ResearchersController@deleteLot')->middleware('auth')->name('deleteLot');

Route::put('researchers/deletephoto', 'ResearchersController@deletePhoto')->middleware('auth')->name('r.deletephoto');

Route::delete('researchers/deletephone', 'ResearchersController@deletePhone')->middleware('auth')->name('r.deletep');

Route::delete('researchers/deleteaddress', 'ResearchersController@deleteAddress')->middleware('auth')->name('r.deletea');

Route::get('researchers/editaddress/{id}', 'ResearchersController@showEditAddress')->middleware('auth')->name('r.showeditaddress');

Route::put('researchers/{id}/editaddress', 'ResearchersController@editAddress')->middleware('auth')->name('r.editaddress');

Route::resource('researchers', 'ResearchersController')->middleware('auth');


//ESTABLISHMENTS
Route::put('establishments/newphone', 'EstablishmentsController@newPhone')->middleware('auth')->name('e.newphone');

Route::put('establishments/newaddress', 'EstablishmentsController@newAddr')->middleware('auth')->name('e.newad');

Route::delete('establishments/deletephone', 'EstablishmentsController@deletePhone')->middleware('auth')->name('e.deletep');

Route::delete('establishments/deleteaddress', 'EstablishmentsController@deleteAddress')->middleware('auth')->name('e.deletea');

Route::get('establishments/editaddress/{id}', 'EstablishmentsController@showEditAddress')->middleware('auth')->name('e.showeditaddress');

Route::put('establishments/{id}/editaddress', 'EstablishmentsController@editAddress')->middleware('auth')->name('e.editaddress');

Route::put('establishments/deletephoto', 'EstablishmentsController@deletePhoto')->middleware('auth')->name('e.deletephoto');

Route::resource('establishments', 'EstablishmentsController')->middleware('auth');

//WORK LOTS

Route::resource('lots', 'LotsController')->middleware('auth');













































// Route::resource('adr_researcher', 'AdrResearcherController')->middleware('auth');

// Route::resource('adr_establishments', 'AdrEstablishmentsController')->middleware('auth');
// Route::resource('est_phone', 'EstPhoneController')->middleware('auth');

// 
// Route::get('researchers/', 'ResearchersController@index')->middleware('auth');
// Route::get('researchers/{id}', 'ResearchersController@show')->middleware('auth');
// Route::put('researchers', 'ResearchersController@edit')->middleware('auth');
// Route::delete('delete/{id}',array('uses' => 'ResearchersController@destroy', 'as' => 'deleteroute'))->middleware('auth');

app/Establishment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Researcher;
use App\Adr_Establishment;
use App\Res_Phone;
use App\Est_Phone;
use DB;

class Establishment extends Model
{

    //use SoftDeletes;

    protected $table = 'establishments';
    protected $fillable = [
        'name',
        'description',
        'national_id',
        'url_logo',
        'email'
    ];

    public function estPhones(){
        return $this->hasMany('App\Est_Phone');
    }

    public function adrEstablishments(){
        return $this->hasMany('App\Adr_Establishment');
    }

    public function researchers(){
        return $this->belongsToMany('App\Researcher', 'establishments_researchers');
    }

}

app/Http/Controllers/EstablishmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Establishment;
use App\Est_Phone;
use App\Adr_Establishment;
use App\Res_Phone;
use App\Researcher;
use DB;
use Auth;

class EstablishmentsController extends Controller
{
    //SHOW//

    public function index()
    {
      $establishments = DB::table('establishments')
      ->orderBy('name', 'asc')->get();  
      
      return view('establishments.index', ['establishments'=> $establishments]);
    }

    public function show(Establishment $establishment)
    {
       $establishemnt = Establishment::find($establishment->id);

       return view('establishments.show', ['establishment' => $establishment]);
    }

    public function showEditAddress($id)
    {
      $adr = Adr_Establishment::find($id);
      return view('establishments.editaddress', ['adr'=> $adr]);
    }
    
    //CREATES//

    public function newPhone(Request $request){

         Est_Phone::create([
         'establishment_id' => $request->input('id'),
         'ddi' => $request->input('ddi'),
         'ddd' => $request->input('ddd'),
         'phone' => $request->input('phone')
        ]);

        return back();
    }

    public function newAddr(Request $request)
    {
        Adr_Establishment::create([
        'establishment_id' => $request->input('id'),
        'latitude' => $request->input('latitude'),
        'longitude' => $request->input('longitude'),
        'address' => $request->input('address'),
        'postal_code' => $request->input('postal_code'),
        'city' => $request->input('city'),
        'country' => $request->input('country'),
        'state' => $request->input('state')
        ]);

        return back();
    } 

    public function create(Establishment $establishment)
    {
        return view('establishments.create', ['establishment'=> $establishment]);
    }

    private function registerPhone(Request $request, $establishmentId)
    {
        return Est_Phone::create([
        'ddi' => $request->input('ddi'),
        'ddd' => $request->input('ddd'),
        'phone' => $request->input('phone'),
        'establishment_id' => $establishmentId
        ]);
    }

    private function registerAddress(Request $request, $establishmentId)
    {
        return Adr_Establishment::create([
        'address' => $request->input('address'),
        'postal_code' => $request->input('postal_code'),
        'city' => $request->input('city'),
        'country' => $request->input('country'),
        'state' => $request->input('state'),
        'latitude' => $request->input('latitude'),
        'longitude' => $request->input('longitude'),
        'establishment_id' => $establishmentId
        ]);
    }

    //SAVES//

    public function store(Request $request)
    {
        if (Auth::check()){
            $establishment = Establishment::create([
            'name' => $request->input('name'),
            'national_id' => $request->input('national_id'),
            'email' => $request->input('email'),
            'description' => $request->input('description'),
            'url_logo' => $request->input('url_logo'),
            'user_id' => Auth::user()->id
            ]);

        $this->registerAddress($request, $establishment->id);
        $this->registerPhone($request, $establishment->id);
            
        if($establishment){
            return redirect()->route('establishments.show', ['establishment' => $establishment->id])
            ->with('success' , 'Instituição criada com sucesso!');
        }
    }
        
    return back()->withInput()->with('error' , 'Algo deu errado :(');
    }

    public function edit($id)
    {
       $establishment = Establishment::find($id);       
       return view('establishments.edit', ['establishment'=> $establishment]);
    }

    public function update(Request $request, $id)
    {
        $establishmentUpdate = Establishment::where('id', $id)
        ->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'national_id' => $request->input('national_id'),
            'description' => $request->input('description')
        ]);

        if($establishmentUpdate){
            return redirect()->route('establishments.show', ['establishment'=>$id]);
        }
        return back()->withInput();
    }

    public function editAddress(Request $request, $id)
    {
        $a_update = Adr_Establishment::where('id', $id)
        ->update([
            'address' => $request->input('address'),
            'postal_code' => $request->input('postal_code'),
            'city' => $request->input('city'),
            'country' => $request->input('country'),
            'state' => $request->input('state'),
            'latitude' => $request->input('latitude'),
            'longitude' => $request->input('longitude')
        ]);
        $establishment = $request->input('establishment_id');
        return redirect()->route('establishments.show' , ['establishment' => $establishment]);
    }
    //DELETES//

    public function destroy($id)
    {
        $find = Establishment::find($id);
        if($find->delete())
        {
            return redirect()->route('establishments.index')
            ->with('success', 'Algo deu certo... instituição removida!');
        }

        return back()->withInput()->with('error', 'Algo deu erado... instituição não removido!');
    }

    public function deletePhone(Request $request)
    {
        Est_Phone::destroy([
            'id' => $request->input('id')
        ]);
        return back();
    }

    public function deleteAddress(Request $request)
    {
        Adr_Establishment::destroy([
            'id' => $request->input('id')
        ]);
        return back();
    }

    public function deletePhoto(Request $request)
    {
        $id = $request->input('id');
        $deletep = Establishment::where('id', $id)
        ->update(['url_logo' => $request->input('url_logo')]);
        
        return back();
    }

    //GMAPS

    public function showMap(Establishment $establishment, $id)
    {
        $locations = DB::table('adr_establishments')->where('id', '=', $id)->get();
        $establishment = DB::table('establishments')->where('id', '=', $locations[0]->establishment_id)->get();
 
        return view('showmap', ['locations' => $locations, 'establishment' => $establishment]);       
    }

    public function showMapVisitor(Establishment $establishment, $id)
    {
        $locations = DB::table('adr_establishments')->where('id', '=', $id)->get();
        $establishment = DB::table('establishments')->where('id', '=', $locations[0]->establishment_id)->get();
 
        return view('visitors.showmap', ['locations' => $locations, 'establishment' => $establishment]);       
    }
    
}

resources/views/establishments/create.blade.php
<!--ESTABLISHMENTS CREATE-->
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                    <div class="card-header"><a style="font-weight:bold">NOVA INSTITUIÇÃO</a></div>     
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <ul class="list-group"></ul>  
                        <li class="list-group-item">
                        <form method="post" action="{{ route('establishments.store') }}">

                          {{ csrf_field() }}
                    
                          
                          <div class="form-row">

                          <div class="form-group col-md-9">
                          <label for="establishment-name">Nome da Instituição*</label>
                          <input type="text" 
                                 class="form-control" 
                                 id="establishment-name" 
                                 placeholder="Nome Completo da Instituição" 
                                 name="name"
                                 maxlength="60"
                                 required
                                 />
                          </div>

                          <div class="form-group col-md-3">
                            <label for="establishment-id">CNPJ*</label>
                            <input type="text" 
                                   class="form-control" 
                                   id="establishment-id" 
                                   placeholder="Apenas números!" 
                                   name="national_id"
                                   maxlength="20"
                                   required
                                   />
                            </div>
                          </div>

                          <div class="form-row">

                        <div class="form-group col-md-4">
                            <label for="establishment-email">Email*</label>
                            <input type="email" 
                                    class="form-control" 
                                    id="establishment-email" 
                                    placeholder="exemplo@email.com"
                                    name ="email"
                                    maxlength="45"
                                    required/>
                        </div>

                        <div class="form-group col-md-1">
                            <label for="establishment-ddi">DDI*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="establishment-ddi" 
                                    placeholder="Ex:55" 
                                    name="ddi"
                                    maxlength="4"
                                    required
                                    />
                        </div>  

                        <div class="form-group col-md-1">
                            <label for="establishment-ddd">DDD*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="establishment-ddd" 
                                    placeholder="Ex:61" 
                                    name="ddd"
                                    maxlength="2"
                                    required
                                    />
                        </div>  

                        <div class="form-group col-md-3">
                            <label for="establishment-phone">Telefone*</label>
                            <input type="text" 
                                    class="form-control" 
                                    id="establishment-phone" 
                                    placeholder="Apenas números!" 
                                    name="phone"
                                    maxlength="10"
                                    required
                                    />
                        </div> 
                        
                        
                        <div class="form-group col-md-3">
                            <label for="establishment-country">País*</label>
                            <input type="text" 
                            class="form-control" 
                            id="establishment-country" 
                            placeholder="Brasil" 
                            name="country"
                            maxlength="45"
                            required
                            />
                        </div>
                        </div>
                         
                        Descrição: <br>
                          <div class="input-group">      
                              <textarea class="form-control" 
                                        aria-label="With textarea"
                                        name="description"
                              ></textarea>
                            </div>
                            <br>

                            <div class="form-row">
                            <div class="form-group col-md-2">
                                <label for="establishment-zip">CEP*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="establishment-zip" 
                                        placeholder="Apenas números!" 
                                        name="postal_code"
                                        maxlength="20"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-7">
                                <label for="establishment-address">Endereço*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="establishment-address" 
                                        placeholder="Ex: Rua das Artes, Bairro Ipê casa 32" 
                                        name="address"
                                        maxlength="90"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-2">
                                <label for="establishment-city">Cidade*</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="establishment-city" 
                                        placeholder="Ex:Brasília" 
                                        name="city"
                                        maxlength="50"
                                        required
                                        />
                            </div>

                            <div class="form-group col-md-1">
                                <label for="establishment-state">UF*</label>
                                <input type="text" 
                                class="form-control" 
                                id="establishment-state" 
                                placeholder="Ex: DF" 
                                name="state"
                                maxlength="2"
                                required
                                />
                                </div>   
                            </div>  

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="establishment-latitude">Latitude</label>
                                    <input type="text" 
                                            class="form-control" 
                                            id="establishment-latitude" 
                                            placeholder="Ex: -15.822395" 
                                            name="latitude"
                                            
                                            />
                                </div>

                            <div class="form-group col-md-6">
                                <label for="establishment-longitude">Longitude</label>
                                <input type="text" 
                                        class="form-control" 
                                        id="establishment-longitude" 
                                        placeholder="Ex: 15.822395" 
                                        name="longitude"
                                        
                                        />
                            </div>
                            </div>
                            <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>
                            <br>
                          <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                        <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-times"></i> Cancelar</a>
                  </form>                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/establishments/edit.blade.php
<!--ESTABLISHMENTS EDIT-->

@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
   <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
      <div class="card-header">Editar dados de <a style="font-weight:bold">{{$establishment->name}}</a></div>                  
          <div class="card-body">
              @if (session('status'))
                  <div class="alert alert-success">
                      {{ session('status') }}
                  </div>
              @endif
              <ul class="list-group"></ul>  
              <li class="list-group-item">
                  <form method="post" action="{{ route('establishments.update', [$establishment->id]) }}">

                    {{ csrf_field() }}
              
                    <input type="hidden" name="_method" value="put">

                      <div class="form-row">
                        <div class="form-group col-md-12">
                          <label for="establishment-name">Nome*</label>
                          <input required 
                                  type="text" 
                                  class="form-control" 
                                  id="establishment-name" 
                                  value="{{ $establishment->name}}"
                                  name="name"  
                                  maxlength="60"                                 
                                  />
                          </div>
                        
                      </div>
                        
                        <div class="form-row">

                          <div class="form-group col-md-6">
                          <label for="establishment-id">CNPJ*</label>
                          <input type="text" 
                                 class="form-control" 
                                 id="establishment-id" 
                                 value="{{ $establishment->national_id}}" 
                                 name="national_id"
                                 maxlength="20"
                                 required
                                 />
                          </div> 
                          
                          <div class="form-group col-md-6">
                            <label for="establishment-email">Email*</label>
                            <input required
                                    type="email" 
                                    class="form-control" 
                                    id="establishment-email" 
                                    value="{{ $establishment->email}}"
                                    name="email"
                                    maxlength="45"
                                    />
                          </div>

                          </div>  

                          <div class="form-row">

                           Descrição: <br>
                          <div class="input-group">      
                              <textarea class="form-control" 
                                        aria-label="With textarea"
                                        name="description"
                          >{{$establishment->description}}</textarea>
                            </div>
                            <br>
                            
  <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>
  <div style="margin-left:80%">
  <a class="btn btn-outline-danger" href="/establishments/{{$establishment->id}}">Cancelar</a>
  <input type="submit" class="btn btn-outline-success"  value="Salvar"/>

  </div>
                    <!--FIM DO FORMULÁRIO-->
                    </form> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/establishments/editaddress.blade.php
{{-- ESTABLISHMENT ADDRESS --}}
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
  <div class="row justify-content-center">
   <div class="col-md-10">
    <div class="card">
     <div class="card-header">Editar Endereço</a></div>                  
      <div class="card-body">
        @if (session('status'))
         <div class="alert alert-success">
          {{ session('status') }}
         </div>
         @endif 

         <form method="post" action="{{ route('e.editaddress', [$adr->id]) }}">

            {{ csrf_field() }}
      
        <input type="hidden" name="_method" value="put">

         <div class="form-row">
           <div class="form-group col-md-2">
            <label for="establishment-zip">CEP*</label>
            <input type="text" 
                    class="form-control" 
                    id="establishment-zip" 
                    value="{{$adr->postal_code}}" 
                    name="postal_code"
                    required
                    />
            </div>

            <div class="form-group col-md-7">
              <label for="establishment-address">Endereço*</label>
              <input type="text" 
                     class="form-control" 
                     id="establishment-address" 
                     value="{{$adr->address}}" 
                     name="address"
                     required
                    />
            </div>

            <div class="form-group col-md-2">
              <label for="establishment-city">Cidade*</label>
              <input type="text" 
                     class="form-control" 
                     id="establishment-city" 
                     value="{{$adr->city}}" 
                     name="city"
                     required
                     />
            </div>

            <div class="form-group col-md-1">
             <label for="establishment-state">UF*</label>
             <input type="text" 
                   class="form-control" 
                   id="establishment-state" 
                   value="{{$adr->state}}" 
                   name="state"
                   required
                   />
                </div>   
            </div>  

            <div class="form-row">
              <div class="form-group col-md-4">
              <label for="establishment-latitude">Latitude</label>
              <input type="text" 
                     class="form-control" 
                     id="establishment-latitude" 
                     value="{{$adr->latitude}}" 
                     name="latitude"  
                    />
              </div>

            <div class="form-group col-md-4">
              <label for="establishment-longitude">Longitude</label>
              <input type="text" 
                     class="form-control" 
                     id="establishment-longitude" 
                     value="{{$adr->longitude}}" 
                     name="longitude"       
                    />
              </div>

              <div class="form-group col-md-4">
                <label for="establishment-country">País*</label>
                <input type="text" 
                       class="form-control" 
                       id="establishment-country" 
                       value="{{$adr->country}}" 
                       name="country"
                       required
                       />
              </div>

              <input type="text" 
                     class="form-control"
                     value="{{$adr->establishment_id}}" 
                     name="establishment_id"
                     style="display:none"
                     required
                     />

            </div>

<a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>

        <div style="margin-left:80%">
            <a class="btn btn-outline-danger" href="{{ URL::previous() }}">Cancelar</a>
            <input type="submit" class="btn btn-outline-success"  value="Salvar"/>
        </div>

        </form> 
</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/establishments/index.blade.php
<!--ESTABLISHMENTS INDEX-->
@extends('layouts.app')

@section('content')
<div class="container" style="margin-top: 3.5%">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">               
        <div class="card-header"><i class="fas fa-university"></i> Banco de Instituições</div>
          <div class="card-body">
            @if (session('status'))
              <div class="alert alert-success">
              {{ session('status') }}
              </div>
            @endif   

            <a class="btn btn-primary" href="/establishments/create"><i class="fas fa-plus"></i> Nova Instituição</a> <br>

            @foreach($establishments as $establishment)
            <br>
            <li class="list-group-item">
            @if ($establishment->url_logo)
            <a href="/establishments/{{ $establishment->id }}">
                <img src="{{ URL($establishment->url_logo) }}" class="p-img">
            </a>
            @else  
            <a href="/establishments/{{ $establishment->id }}">
              <img src="{{ URL('image/empty.png') }}" class="p-img">
            </a>
            @endif 
            <a href="/establishments/{{ $establishment->id }}">  
            {{ $establishment->name }}
            </a>                           
            @endforeach 
            </li>                   
            <br>
             
</div>     
</div>
</div>
</div>
</div>

@endsection