routes/web.php
<?php

Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

//VISITORS

Route::get('home2', 'VisitorsController@homeVisitors')->name('v.home');

        //RESEARCHERS
        Route::get('home2/researchers', 'VisitorsController@indexResearchers')->name('r.index');
        Route::get('home2/researchers/{id}', 'VisitorsController@showResearchers')->name('r.show');

        //LOTS
        Route::get('home2/lots', 'VisitorsController@indexLots')->name('l.index');
        Route::get('home2/lots/{id}', 'VisitorsController@showLots')->name('l.show');

        //ESTABLISHMENTS
        Route::get('home2/establishments', 'VisitorsController@indexEstablishments')->name('e.index');
        Route::get('home2/establishments/{id}', 'VisitorsController@showEstablishments')->name('e.show');
        Route::get('map2/{id}', 'EstablishmentsController@showMapVisitor');

//GEOLOCATION
Route::get('map/{id}', 'EstablishmentsController@showMap')->middleware('auth');


//IMAGES
Route::post('imagePostEstablishment', 'ImageController@imagePostEstablishments')->middleware('auth')->name('imagePostEstablishment');

Route::post('imagePostResearcher', 'ImageController@imagePostResearchers')->middleware('auth')->name('imagePostResearcher');


//HOME
Route::resource('home', 'HomeController')->middleware('auth');

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');


//RESEARCHERS
Route::put('researchers/newphone', 'ResearchersController@newPhone')->middleware('auth')->name('r.newphone');

Route::put('researchers/newadr', 'ResearchersController@newAddr')->middleware('auth')->name('r.newad');

Route::put('researchers/link', 'ResearchersController@link')->middleware('auth')->name('r.link');

Route::put('researchers/tolot', 'ResearchersController@toLot')->middleware('auth')->name('r.lot');

Route::delete('researchers/unlink', 'ResearchersController@unlink')->middleware('auth')->name('unlink');

Route::delete('researchers/deletelot', 'ResearchersController@deleteLot')->middleware('auth')->name('deleteLot');

Route::put('researchers/deletephoto', 'ResearchersController@deletePhoto')->middleware('auth')->name('r.deletephoto');

Route::delete('researchers/deletephone', 'ResearchersController@deletePhone')->middleware('auth')->name('r.deletep');

Route::delete('researchers/deleteaddress', 'ResearchersController@deleteAddress')->middleware('auth')->name('r.deletea');

Route::get('researchers/editaddress/{id}', 'ResearchersController@showEditAddress')->middleware('auth')->name('r.showeditaddress');

Route::put('researchers/{id}/editaddress', 'ResearchersController@editAddress')->middleware('auth')->name('r.editaddress');

Route::resource('researchers', 'ResearchersController')->middleware('auth');


//ESTABLISHMENTS
Route::put('establishments/newphone', 'EstablishmentsController@newPhone')->middleware('auth')->name('e.newphone');

Route::put('establishments/newaddress', 'EstablishmentsController@newAddr')->middleware('auth')->name('e.newad');

Route::delete('establishments/deletephone', 'EstablishmentsController@deletePhone')->middleware('auth')->name('e.deletep');

Route::delete('establishments/deleteaddress', 'EstablishmentsController@deleteAddress')->middleware('auth')->name('e.deletea');

Route::get('establishments/editaddress/{id}', 'EstablishmentsController@showEditAddress')->middleware('auth')->name('e.showeditaddress');

Route::put('establishments/{id}/editaddress', 'EstablishmentsController@editAddress')->middleware('auth')->name('e.editaddress');

Route::put('establishments/deletephoto', 'EstablishmentsController@deletePhoto')->middleware('auth')->name('e.deletephoto');

Route::resource('establishments', 'EstablishmentsController')->middleware('auth');

//WORK LOTS

Route::resource('lots', 'LotsController')->middleware('auth');













































// Route::resource('adr_researcher', 'AdrResearcherController')->middleware('auth');

// Route::resource('adr_establishments', 'AdrEstablishmentsController')->middleware('auth');
// Route::resource('est_phone', 'EstPhoneController')->middleware('auth');

// 
// Route::get('researchers/', 'ResearchersController@index')->middleware('auth');
// Route::get('researchers/{id}', 'ResearchersController@show')->middleware('auth');
// Route::put('researchers', 'ResearchersController@edit')->middleware('auth');
// Route::delete('delete/{id}',array('uses' => 'ResearchersController@destroy', 'as' => 'deleteroute'))->middleware('auth');

app/Lot.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Researcher;

class Lot extends Model
{
    protected $table = 'lots';

    protected $fillable = [
        'name',
        'description'
    ];

    public $timestamps = false;

    public function researchers(){
        return $this->belongsToMany('App\Researcher', 'researchers_lots');
    }
}

app/Http/Controllers/LotsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Lot;
use App\Researcher;
use App\Researchers_Lots as Rl;
use Auth;
use DB;

class LotsController extends Controller
{
    public function index()
    {
        $lots = DB::table('lots')
        ->orderBy('name', 'asc')->get();   

         return view('lots.index', ['lots'=> $lots]);
    }

    public function show($id)
    {
        $lot = Lot::find($id); 
        $researchers = Researcher::all();
        $rl = Rl::where('researcher_id','=', $id)->get();

        return view('lots.show', ['lot'=> $lot, 'researchers'=> $researchers, 'rl'=> $rl]);
    }

    public function create(Lot $lot)
    {   
        return view('lots.create', ['lot'=> $lot]);
    }

    public function store(Request $request)
    {
        if (Auth::check()){
            $lot = Lot::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'user_id' => Auth::user()->id
            ]);
            
        if($lot){
            return redirect()->route('lots.show', ['lot' => $lot->id]);
            }
    }
        
    return back();
    }

    public function edit($id)
    {
       $lot = Lot::find($id);       
       return view('lots.edit', ['lot'=> $lot]);
    }

    public function update(Request $request, $id)
    {
        $lotUpdate = Lot::where('id', $id)
        ->update([
            'name' => $request->input('name'),
            'description' => $request->input('description')
        ]);

        if($lotUpdate){
            return redirect()->route('lots.show', ['lot'=>$id]);
        }
        return redirect()->route('lots.show', ['lot'=>$id]);
    }

    public function destroy($id)
   {
       $find = Lot::find($id);
       if($find->delete())
       {
            return redirect()->route('lots.index');
       }
       return back();
   }

}

resources/views/lots/create.blade.php
<!--LOTS CREATE-->
@extends('layouts.app')

@section('content')


<div class="container" >
  <div class="row justify-content-center" style="margin-top: 5.5%">
    <div class="col-md-10">
        <div class="card">
          <div class="card-header"><a style="font-weight:bold">NOVO LOTE DE TRABALHO</a></div>                  
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                    
                    <ul class="list-group"></ul>  
                    <li class="list-group-item">
                    <form method="post" action="{{ route('lots.store') }}">

                        {{ csrf_field() }}
                
                        
                        <div class="form-row">

                        <div class="form-group col-md-6">
                        <label for="lot-name">Nome do lote*</label>
                        <input type="text" 
                                class="form-control" 
                                id="lot-name" 
                                placeholder="Nome/n° do lote" 
                                name="name"
                                maxlength="45"
                                required
                                />
                        </div>

                        <div class="form-group col-md-6">
                        <label for="lot-id">Descrição</label>
                        <input type="text" 
                                class="form-control" 
                                id="lot-description" 
                                placeholder="Sobre este lote" 
                                name="description"
                                maxlength="45"
                                />
                        </div>  
                        
                        <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>
                        </div>                                     
                            
                        <br>
                        <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                    <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-times"></i> Cancelar</a>
                </form>                                                    
              </div>
            </div>
        </div>
    </div>
</div>

@endsection


                   

resources/views/lots/edit.blade.php
<!--LOTS EDIT-->

@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.8%">
   <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
      <div class="card-header">Editar dados de <a style="font-weight:bold">{{$lot->name}}</a></div>                  
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <ul class="list-group"></ul>  
            <li class="list-group-item">
                <form method="post" action="{{ route('lots.update', [$lot->id]) }}">

                {{ csrf_field() }}
            
                <input type="hidden" name="_method" value="put">
<div class="row">
                    <div class="form-group col-md-6">
                    <label for="lot-name">Nome do lote*</label>
                    <input type="text" 
                            class="form-control" 
                            id="lot-name" 
                            value="{{$lot->name}}"
                            name="name"
                            maxlength="45"
                            required
                            />
                    </div>

                    <div class="form-group col-md-6">
                    <label for="lot-id">Descrição</label>
                    <input type="text" 
                            class="form-control" 
                            id="lot-description" 
                            value="{{$lot->description}}"
                            name="description"
                            maxlength="45"
                            />
                    </div> 
                    </div> 
                        
                <a style="margin-left:1%"><i>Favor preencher <b>corretamente</b> todos os campos que possuam (*)!</i></a>
                <br>                                  
                <a class="btn btn-outline-danger" href="/lots/{{$lot->id}}">Cancelar</a>
                <input type="submit" class="btn btn-outline-success"  value="Salvar"/>
                    <!--FIM DO FORMULÁRIO-->
                    </form> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/lots/index.blade.php
<!--ESTABLISHMENTS INDEX-->
@extends('layouts.app')

@section('content')
<div class="container" style="margin-top: 3.5%">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">               
        <div class="card-header"><i class="fas fa-briefcase"></i> Lotes de Trabalho</div>
          <div class="card-body">
            @if (session('status'))
              <div class="alert alert-success">
              {{ session('status') }}
              </div>
            @endif   

            <a class="btn btn-primary" href="/lots/create"><i class="fas fa-plus"></i> Novo Lote de Trabalho</a> <br>

            @foreach($lots as $lot)
            <br>
            <li class="list-group-item">

            <a href="/lots/{{ $lot->id }}">  
            {{ $lot->name }}
            </a>                           
            @endforeach 
            </li>                   
            <br>
             
</div>     
</div>
</div>
</div>
</div>

@endsection

resources/views/lots/show.blade.php
<!--LOTS SHOW-->
@extends('layouts.app')

@section('content')

<div class="container" style="margin-top: 3.5%">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
        <div class="card-header">
          
          Dados de <a style="font-weight:bold">{{$lot->name}}</a></div>                  
          <div class="card-body">
              @if (session('status'))
                  <div class="alert alert-success">
                      {{ session('status') }}
                  </div>
              @endif  
              
            <div class="card-header" style="font-weight:bold; font-size:small"><i class="fas fa-info-circle"></i> Sobre este Lote de Trabalho</div>
            <div class="card" style="border-radius: 0%">
            <div style="margin-left:5px">
              Nome: {{$lot->name}} <br>
              Descrição: {{$lot->description}} <br>

              Membros: 
                @foreach($lot->researchers as $res)
                <a href="/researchers/{{$res->id}}">   
                {{$res->name}}
                </a>|
                @endforeach

            </div>
            </div>
<br>
              <div style="margin-left: 578px">
              <form method="POST">
              <a class="btn btn-primary" href="/lots"><i class="fas fa-bars"></i> Lotes de Trabalho</a>
              <a class="btn btn-warning" href="/lots/{{$lot['id']}}/edit">
              <i class="far fa-edit"></i> Editar</a>
              <input type="hidden" name="_method" value="DELETE" >
              <input type="hidden" name="_token" value="{{ csrf_token() }}" >
              <input type="hidden" name="id" value = "{{$lot['id']}}">
              <input type="hidden" name="form_type" value = "deleteRes">
              <input
                  onclick="return confirm('Deletar TODOS os registros de {{$lot->name}}?');"
                  class="btn btn-danger"
                  value="Deletar"
                  style="cursor: pointer;"
                  type="submit"
              >
              </form>
              </div>
   </div>
  </div>                          
   </div>
    </div>
     </div>
</div>
</div>


@endsection